aws ecr --region us-east-1 create-repository --repository-name myimage
aws ecr --region us-east-2 create-repository --repository-name myimage
aws ecr --region us-west-1 create-repository --repository-name myimage
aws ecr --region us-west-2 create-repository --repository-name myimage
aws ecr --region ap-southeast-1 create-repository --repository-name myimage
aws ecr --region ap-northeast-1 create-repository --repository-name myimage
aws ecr --region ap-northeast-2 create-repository --repository-name myimage
aws ecr --region eu-central-1 create-repository --repository-name myimage
aws ecr --region eu-west-1 create-repository --repository-name myimage
aws ecr --region eu-west-3 create-repository --repository-name myimage
aws ecr --region eu-north-1 create-repository --repository-name myimage
aws ecr --region sa-east-1 create-repository --repository-name myimage
aws ecr --region ap-south-1 create-repository --repository-name myimage
aws ecr --region eu-west-2 create-repository --repository-name myimage
aws ecr --region ca-central-1 create-repository --repository-name myimage
aws ecr --region ap-northeast-3 create-repository --repository-name myimage
aws ecr --region ap-southeast-2 create-repository --repository-name myimage

aws ecr --region af-south-1 create-repository --repository-name myimage
aws ecr --region ap-east-1 create-repository --repository-name myimage
aws ecr --region ap-south-2 create-repository --repository-name myimage
aws ecr --region ap-southeast-3 create-repository --repository-name myimage
aws ecr --region ap-southeast-4 create-repository --repository-name myimage
aws ecr --region eu-south-1 create-repository --repository-name myimage
aws ecr --region eu-south-2 create-repository --repository-name myimage
aws ecr --region eu-central-2 create-repository --repository-name myimage
aws ecr --region me-south-1 create-repository --repository-name myimage
aws ecr --region me-central-1 create-repository --repository-name myimage
