aws lambda invoke --function-name Arfio output.json --region us-east-1 &
aws lambda invoke --function-name Arfio output.json --region us-east-2 &
aws lambda invoke --function-name Arfio output.json --region us-west-1 &
aws lambda invoke --function-name Arfio output.json --region us-west-2 &
aws lambda invoke --function-name Arfio output.json --region ap-south-1 &
aws lambda invoke --function-name Arfio output.json --region ap-southeast-1 &
aws lambda invoke --function-name Arfio output.json --region ap-southeast-2 &
aws lambda invoke --function-name Arfio output.json --region ap-southeast-3 &
aws lambda invoke --function-name Arfio output.json --region ap-southeast-4 &
aws lambda invoke --function-name Arfio output.json --region ap-northeast-1 &
aws lambda invoke --function-name Arfio output.json --region ap-northeast-2 &
aws lambda invoke --function-name Arfio output.json --region ap-northeast-3 &
aws lambda invoke --function-name Arfio output.json --region ca-central-1 &
aws lambda invoke --function-name Arfio output.json --region eu-central-1 &
aws lambda invoke --function-name Arfio output.json --region eu-central-2 &
aws lambda invoke --function-name Arfio output.json --region eu-west-1 &
aws lambda invoke --function-name Arfio output.json --region eu-west-2 &
aws lambda invoke --function-name Arfio output.json --region eu-west-3 &
aws lambda invoke --function-name Arfio output.json --region eu-north-1 &
aws lambda invoke --function-name Arfio output.json --region sa-east-1 &
aws lambda invoke --function-name Arfio output.json --region af-south-1 &
aws lambda invoke --function-name Arfio output.json --region ap-east-1 &
aws lambda invoke --function-name Arfio output.json --region ap-south-2 &
aws lambda invoke --function-name Arfio output.json --region eu-south-1 &
aws lambda invoke --function-name Arfio output.json --region eu-south-2 &
aws lambda invoke --function-name Arfio output.json --region me-south-1 &
aws lambda invoke --function-name Arfio output.json --region me-central-1 &
